config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root 'welcome#index'
  resources :users
  resources :sessions
  resources :branches do
    collection  do           #saca del route a upload para evitar que pida el Id de branche /quita el nested de los hijos evitando la rerencia
      post 'import'  => 'branches#import'   #obteniendo ruta para upload
    end
      resources :employees do
        collection do
          post 'import'  => 'employees#import'
        end
      end
    end
  get 'users/new'

end

app/models/branch.rb
# encoding: utf-8
class Branch < ActiveRecord::Base
#Validacion para que el nombre de la sucursal sea por lo menos de 5 caract
  belongs_to :user
  has_many :employees, dependent: :destroy

  accepts_nested_attributes_for :employees, allow_destroy: true, limit: 5

  validates :nombre, presence: true,
                     length: { minimum: 2 }

  validates_presence_of :numExt, :on => :create
  validates_presence_of :numInt, :on => :create
  validates_numericality_of :cp, :on => :create
  #before_save :default_name, :if => lambda { |branch| branch[:nombre].blank? }


  before_validation :no_empty, :on => :create

  #metodo que busca y regresa las sucursales pertenecientes a un user_id del empleado (ver en sessionControler)
  def self.sucursales_por_usuario(user_id)
    Branch.where(user_id: user_id)
  end


  def self.import(file, user_id)
    #se recibe la variable user_id del controlador como parameto a importar
    @errors = []  #<--- array para acumular errores
    spreadsheet = Roo::Spreadsheet.open(file.path, extension: :xlsx)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      branch = find_or_initialize_by(id: row["id"])
      branch.attributes = row.to_hash.slice(*row.to_hash.keys)
      branch.user_id = user_id
      if branch.valid?
        branch.save!
      else
        branch.errors.full_messages.each do |message|
          @errors << "La información de la Fila: #{i}, columna: #{message}:"
        end
      end
    end
    @errors
  end

      #se asigna la variable user_id al parametro de user id de la sucursal





  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


  private

  def no_empty
    @flag = true
    if self.nombre.present?
    else
      errors.add(:base, 'Nombre, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.calle.present?
    else
      errors.add(:base, 'Calle, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.numExt.present?
    else
      errors.add(:base, 'Numero Exterior, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.numInt.present?
    else
      errors.add(:base, 'Numero Interior, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.cp.present?
    else
      errors.add(:base, 'Codigo Postal, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.ciudad.present?
    else
      errors.add(:base, 'Ciudad, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.pais.present?
    else
      errors.add(:base, 'Pais, Esta vacio o es invalido || CALLBACK ||')
      @flag = false
    end
    if self.cp.to_s.match(/(\d)/)
    else
      errors.add(:base, 'Codigo Postal, Es valor no numerico o invalido || CALLBACK ||')
      @flag = false
    end
    @flag
  end


end

app/controllers/branches_controller.rb
# encoding: UTF-8
class BranchesController < ApplicationController

  #before_action :validates,  except: [:index]
  def index
    @branches = Branch.sucursales_por_usuario(current_user.id)   #se enlistan las sucursale spara la descarga
    respond_to do |format|
      format.html
      format.xlsx  {
    response.headers['Content-Disposition'] = 'attachment; filename="Listado_sucursales.xlsx"'
    }
    end
  end

  def new
    @branch = Branch.new
  end

  def create
    @branch = current_user.branches.new(branch_params)
    @branch.user_id = current_user.id  #asignando user_id de branch perteneciente al current user
    if @branch.save
      redirect_to @branch
    else
      render 'new'
    end
  end

  def show
    @branch = Branch.find(params[:id])
    @sucursales = Branch.sucursales_por_usuario(current_user.id) #asignando a la varibale sucursales el valor del metodo self.sucursalespor usuario
  end

  def edit
    @branch = Branch.find(params[:id])
  end

  def update
    @branch = Branch.find(params[:id])
    if @branch.update(branch_params)
      redirect_to branches_path
    else
      render 'edit'
    end
  end

  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy
    redirect_to branches_path
  end

  def import
    @errors =Branch.import(params[:branch][:file], current_user.id) #se agrego [:branch] para buscar :file dentro de la variable
      if @errors.present?
        redirect_to branches_path, notice: 'Error: ' + errors + '   : El archivo no se pudo importar!!'
      else
        redirect_to branches_path, notice: "-------> Sucursales importadas con Exito!"
      end
  end
  def errors
    @errors.map(&:inspect).join()
  end


  private

    def branch_params
      params.require(:branch).permit(:nombre, :calle, :numExt, :numInt, :cp, :ciudad, :pais, employees_attributes:[:nombre, :rfc, :puesto, :id])
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for @branch do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited
        this article from being saved:</h2>
        <ul>
          <% @branch.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
    <div align="center">
      <p>
        <%= f.label :nombre  %><br>
        <%= f.text_field :nombre, placeholder:"Nombre" %>
      </p>
      <p>
        <%= f.label :calle %><br>
        <%= f.text_area :calle %>
      </p>
      <p>
        <%= f.label :numExt %><br>
        <%= f.text_area :numExt %>
      </p>
      <p>
        <%= f.label :numInt %><br>
        <%= f.text_area :numInt, autofocus: true %>
      </p>
      <p>
        <%= f.label :cp %><br>
        <%= f.text_area :cp %>
      </p>
      <p>
        <%= f.label :ciudad %><br>
        <%= f.text_area :ciudad %>
      </p>
      <p>
        <%= f.label :pais %><br>
        <%= f.text_area :pais %>
      </p>
      <p>
      <%= f.nested_fields_for :employees do |ff| %>
      <p>
        <%= f.label :Nombre %><br>
        <%= ff.text_field :nombre %>
      </p>
        <p>
          <%= f.label :RFC %><br>
          <%= ff.text_field :rfc %>
        </p>
        <p>
          <%= f.label :Puesto %><br>
          <%= ff.text_field :puesto %>
        </p>
        <%= ff.remove_nested_fields_link 'Ocultar Campos.' %>
        <% end %>
      </p>
    </div>


    <div  align="center">
      <p class="button"><%= submit_tag "Enviar" %> <%= button_tag "Reset", type: :reset %></p>
      <p><%= f.add_nested_fields_link :employees, 'Agregar empleado' %></p>
    </div>
<%end %>

app/views/branches/edit.html.erb
<div align="center" >

  <h1>Editar sucursal </h1>

  <%= render 'form' %>

    <%= link_to "Atras", branches_path %>

  </script>

</div>

app/views/branches/index.html.erb
<h1 align="center"> Listado de sucursales </h1>
  <p aling="left">
    <%= link_to "Inicio", root_path %>
  </p>
<table align="center">
    <tr>
      <th> Nombre </th>
      <th> Calle </th>
      <th> Numero Exterior</th>
      <th> Numero Interior</th>
      <th> Codigo Postal</th>
      <th> Ciudad </th>
      <th> Pais </th>
      <th> usuario </th>
      <th>ID sucursal</th>
      <th colspan="2"></th>
    </tr>

    <% @branches.each do |branch| %>

      <tr>
        <td align="center"><%= branch.nombre %></td>
        <td align="center"><%= branch.calle %></td>
        <td align="center"><%= branch.numExt %></td>
        <td align="center"><%= branch.numInt %></td>
        <td align="center"><%= branch.cp %></td>
        <td align="center"><%= branch.ciudad %></td>
        <td align="center"><%= branch.pais %></td>
        <td align="center"><%= branch.user_id %></td>
        <td align="center"><%= branch.id %></td>
        <td><%= link_to 'Mostrar ', branch_path(branch) %></td>
        <td><%= link_to 'Editar', edit_branch_path(branch) %></td>
        <td><%= link_to 'Eliminar', branch_path(branch),
                    method: :delete, data: { confirm: 'Estas seguro que deseas eliminar?' } %></td>
      </tr>
    <% end %>
  </table>
  <div  align="right">
    <%= link_to "agregar sucursal", new_branch_path %>
  </div>
  <% if @errors %>
   <% @errors.each do |message| %>
    <%= message %>
   <% end %>
  <% end %>
  <h1>Importar y Exportar sucursales</h1>
  <h3> >> Exportar Listado de sucursales  </h3>
  <%= link_to 'Descargar Listado de Sucursales en formato Excel (*.xlsx)', branches_path(format: :xlsx) %>
  <h3> >> Subir listado de sucursales</h3>
   <p>
    <%= form_for :branch, :url => import_branches_path(:controller => 'Branches', :action => 'import', :multipart => true) do |f| %>
      <%= f.file_field :file %>
    <p class="button"><%= f.submit 'Subir archivo'%></p>
    <% end %>
  </p>
  <p>
    ---> Subir archivo (*.xls)  <%= link_to "Plantilla para sucursales", "https://drive.google.com/open?id=0B_eP4g871CrsU250VWRFaEx4Vjg", :target => "_blank" %>
  </p>

app/views/branches/new.html.erb
<h1 align="center"> Agregar Nueva sucursal </h1>
<%= link_to "Inicio", root_path %>
  <%= render 'form' %>
  <p align="center"><%= link_to "Listado de sucursales", branches_path %></p>

app/views/branches/show.html.erb
<div align="center">
  <h1>Sucursal :</h1>
  <table>
    <tr>
      <th><strong>Nombre:</strong></th>
      <th><strong>Calle:</strong></th>
      <th><strong>Numero Ext.:</strong></th>
      <th><strong>Numero Int.:</strong><br></th>
      <th><strong>Codigo Postal:</strong></th>
      <th><strong>Ciudad:</strong><br></th>
      <th><strong>Pais:</strong></th>
      <th><strong>User ID:</strong></th>
    </tr>
    <tr>
       <td align="center"><%= @branch.nombre %></td>
       <td align="center"><%= @branch.calle %></td>
       <td align="center"><%= @branch.numExt %></td>
       <td align="center"><%= @branch.numInt %></td>
       <td align="center"><%= @branch.cp %></td>
       <td align="center"><%= @branch.ciudad %></td>
       <td align="center"><%= @branch.pais %></td>
       <td align="center"><%= @branch.user_id %></td>
     </tr>
   </table>

  <p>
    Esta sucursal pertenece al usuario : <%= @branch.user.nombre %>
  </p>
  <p>
    Email del usuario : <%= @branch.user.email %>
  </p>

  <h2>Empleados agregados a esta sucursal</h2>
  <%= render @branch.employees %>

  <h2> Agregar emplado a sucursal </h2>

    <%= render "employees/form" %>
    <div>
      <h3> >> Exportar Listado de sucursales  </h3>
      <%= link_to 'Exportar empleados formato excel Excel (*.xlsx)',  branch_employees_path(@branch, format: :xlsx) %>
      <h3> >> Subir listado de sucursales</h3>
      <p>
       <%= form_for :employee, :url => import_branch_employees_path(:branch_id => @branch, :controller => 'employees', :action => 'import', :multipart => true) do |f| %>
         <%= f.file_field :file %>
       <p class="button"><%= f.submit 'Subir archivo'%></p>
       <% end %>
     </p>
    </div>

  <% unless @branch.user.nil? %>
  <% end %>
  <%= link_to "Listado de sucursales", branches_path %>

  <%= link_to "agregar sucursal", new_branch_path %>
</div>