config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root 'welcome#index'
  resources :users
  resources :sessions
  resources :branches do
    collection  do           #saca del route a upload para evitar que pida el Id de branche /quita el nested de los hijos evitando la rerencia
      post 'import'  => 'branches#import'   #obteniendo ruta para upload
    end
      resources :employees do
        collection do
          post 'import'  => 'employees#import'
        end
      end
    end
  get 'users/new'

end

app/models/employee.rb
# encoding: utf-8
class Employee < ActiveRecord::Base

  belongs_to :branch

  validates_presence_of :nombre, :on => :create
  validates_presence_of :rfc, :on => :create
  before_validation :check, :on => :create

  def empleados_por_sucursal(branch_id)
    Employee.where(branch_id: branch_id)
  end

  def self.import(file,branch_id)
    #se recibe la variable user_id del controlador como parameto a importar
    @errors = []  #<--- array para acumular errores
    spreadsheet = Roo::Spreadsheet.open(file.path, extension: :xlsx)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      employee = find_or_initialize_by(id: row["id"])
      employee.attributes = row.to_hash.slice(*row.to_hash.keys)
      employee.branch_id = branch_id
      if employee.valid?
        employee.save!
      else
        employee.errors.full_messages.each do |message|
          @errors << "La información de la Fila: #{i}, columna: #{message}:"
        end
      end
    end
    @errors
  end
      #se asigna la variable user_id al parametro de user id de la sucursal
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  private

  def check
    @flag = true
    if self.nombre.present?
    else
      errors.add(:base, 'Nombre, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.rfc.present?
    else
      errors.add(:base, 'RFC, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    if self.puesto.present?
    else
      errors.add(:base, 'Puesto, Esta vacio o es invalido  || CALLBACK ||')
      @flag = false
    end
    @flag
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @branch = Branch.find(params[:branch_id])
    @employees = @branch.employees
  end

  def show
    @branch = Branch.find(params[:branch_id])
    @employee =Branch.empleados_por_sucursal(branch_id)
  end
 def new
   @employee = Employee.new
 end

 def create
     @branch = Branch.find(params[:branch_id])
     @Employee = @branch.employees.create(employee_params)
     redirect_to branch_path(@branch)
 end

 def edit
     @branch = Branch.find(params[:branch_id])
 end

 def update
   @branch = Branch.find(params[:branch_id])
   if @employee = @branch.employees.update(employee_params)
      redirect_to @branch
   else
     render 'edit'
   end
 end

 def destroy
   @branch = Branch.find(params[:branch_id])
   @employee = @branch.employees.find(params[:id])
   @employee.destroy
   redirect_to branch_path(@branch)
 end

 def import
   @errors = Employee.import(params[:employee][:file],params[:branch_id]) #se agrego [:branch] para buscar :file dentro de la variable
     if @errors.present?
       redirect_to branch_path(params[:branch_id]), notice: 'Error: ' + errors + '   : El archivo no se pudo importar!!'
     else
       redirect_to branch_path(params[:branch_id]), notice: "-------> Empleados importados con Exito!"
     end
 end

 def errors
   @errors.map(&:inspect).join()
 end

   private
   def employee_params
     params.require(:employee).permit(:nombre, :rfc, :puesto)
   end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<table align="center">
  <tr>
     <th> Nombre Empleado : </th>
     <th> RFC: </th>
     <th> Puesto: </th>
     <th colspan="2"></th>
  </tr>
      <tr>
        <td align="center"><%= employee.nombre %></td>
        <td align="center"><%= employee.rfc %></td>
        <td align="center"><%= employee.puesto %></td>

      </tr>
  </table>
  <%= link_to 'Eliminar empleado', [employee.branch, employee],
               method: :delete,
               data: { confirm: 'Estas seguro que deseas eliminar este empleado?' } %>

app/views/employees/_form.html.erb
<%= form_for ([@branch, @branch.employees.build]) do |f| %>


  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %><br>
  </p>
  <p>
    <%= f.label :rfc %><br>
    <%= f.text_field :rfc %><br>
  </p>
  <p>
    <%= f.label :puesto %><br>
    <%= f.text_field :puesto %><br>
  </p>

  <p><%= select_tag 'sucursales', options_from_collection_for_select(@sucursales, :id, :nombre) %></p>

  <p>
    <%= f.submit 'Crear Empleado' %>
  </p>
  <% end %>

app/views/employees/edit.html.erb
<h1> Editar empleado </h1>

<%= render :partial => 'employee/form' %>

  <%= link_to "atras", branches_path %>

app/views/employees/index.html.erb
<table align="center">
    <tr>
      <th> Nombre Empleado : </th>
      <th> RFC: </th>
      <th> Puesto: </th>
      <th colspan="2"></th>
    </tr>



      <tr>
        <td align="center"><%= employee.nombre %></td>
        <td align="center"><%= employee.rfc %></td>
        <td align="center"><%= employee.puesto %></td>

      </tr>
  </table>
  <%= link_to 'Eliminar empleado', [employee.branch, employee],
               method: :delete,
               data: { confirm: 'Estas seguro que deseas eliminar este empleado?' } %>

app/views/employees/new.html.erb
<h1> Nueva Empleado </h1>

<%= render 'form' %>

<%= link_to "Atras", branches_path %>


</script>