config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root 'welcome#index'
  resources :users
  resources :sessions
  resources :branches do
    collection  do           #saca del route a upload para evitar que pida el Id de branche /quita el nested de los hijos evitando la rerencia
      post 'import'  => 'branches#import'   #obteniendo ruta para upload
    end
      resources :employees do
        collection do
          post 'import'  => 'employees#import'
        end
      end
    end
  get 'users/new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema</title>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-1.12.4.min.js', 'application' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user_nav"  align="right">
    <% if current_user %>
      Sesión iniciada como <%= current_user.email %>.
      <%= link_to "Cerrar Sesion", log_out_path %>
    <% else %>
      <%= link_to "Registro", sign_up_path %> or
      <%= link_to "Iniciar Sesion", log_in_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

  <%= yield %>
  <%= insert_paloma_hook %>

<script type="text/javascript">
  $(document).ready(function() {
    Paloma.start();
    console.log("probando doc listo");
  })
</script>


</body>
</html>